version: "3"
services:
  backend:
    build: "backend"
    ports:
      - 8088:8088
    env_file:
      - backend/.env

  frontend:
    build: frontend
    ports:
      - 3000:3000
    environment:
      - BACKEND_URL=http://backend:8088
    depends_on:
      backend:
        condition: service_started
